### ISSUE TITLE
Lyrics sources

### ISSUE THREAD

**Issue by aymenitc** [khaouitiabdelhakim/AILyrics-JS#1]
Hello,
I used your library. It only work when google shows the lyric from lyricfind.com but when google shows lyrics from other sources like musicmatch it doesn't work.

Thank you and appreciate your work 😊

**Comment by khaouitiabdelhakim** [comment]
Hi bro, thanks for using my library
But this was designed to work regardless of the website, it checks first google if it provides the lyrics else it pass through all the suggested web sources ( in that point it just an approximate approach to find lyrics).
It is a long time ago i don't use it. I see or you can pass through the code and see how you can fix it hhh.


Thanks in advance.

On Jul 5, 2024 21:11, aymenitc ***@***.***> wrote:

Hello,
I used your library. It only work when google shows the lyric from lyricfind.com but when google shows lyrics from other sources like musicmatch it doesn't work.

Thank you and appreciate your work 😊
